### PR TITLE
Fix/better asset naming

### PR DESCRIPTION
**Pull request by jspaleta**
Changes:
* Update all Dockerfile build args to use a sane fallback for ruby version and asset version
* Update all Dockerfile to build assets that encode asset version, ruby version,target platform, and target arch
* update travisCI scripting to match asset naming changes.
* Update alpine Dockerfile to include ssl related libraries in the asset libraries, to make sure libraries are available for ruby plugin assets that use the runtime asset.
* update build instructions in README to match changes

### CODE REVIEW

**Comment by jspaleta** [comment]
closes #7

**Comment by jspaleta** [comment]
not sure what is going on with Travis at the moment. I've successfully run build.sh and checksum.sh to completion locally.

**Review by cwjohnston — APPROVED** [review]
Looks good to me! :shipit:

**Comment by cwjohnston** [comment]
Closes #12

**Pull request merged**
